services:
  # Database Services - Separate databases for each service
  postgres-user:
    image: postgres:15
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_postgres_password_2024}
    ports:
      - "5432:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
      - ./docker/postgres/init-user-service.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sharklearning-network

  postgres-content:
    image: postgres:15
    environment:
      POSTGRES_DB: content_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_postgres_password_2024}
    ports:
      - "5433:5432"
    volumes:
      - postgres_content_data:/var/lib/postgresql/data
      - ./docker/postgres/init-content-service.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sharklearning-network

  postgres-progress:
    image: postgres:15
    environment:
      POSTGRES_DB: progress_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_postgres_password_2024}
    ports:
      - "5434:5432"
    volumes:
      - postgres_progress_data:/var/lib/postgresql/data
      - ./docker/postgres/init-progress-service.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sharklearning-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - sharklearning-network

  # API Gateway
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-default_jwt_secret_for_development_only}
    depends_on:
      - redis
    volumes:
      - ./services/api-gateway:/app
      - /app/node_modules
    networks:
      - sharklearning-network

  # User Service
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-secure_postgres_password_2024}@postgres-user:5432/user_service_db
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-default_jwt_secret_for_development_only}
    depends_on:
      - postgres-user
      - redis
    volumes:
      - ./services/user-service:/app
      - /app/node_modules
    networks:
      - sharklearning-network

  # Content Service
  content-service:
    build:
      context: ./services/content-service
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-secure_postgres_password_2024}@postgres-content:5432/content_service_db
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-default_jwt_secret_for_development_only}
    depends_on:
      - postgres-content
      - redis
    volumes:
      - ./services/content-service:/app
      - /app/node_modules
    networks:
      - sharklearning-network

  # Progress Service
  progress-service:
    build:
      context: ./services/progress-service
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-secure_postgres_password_2024}@postgres-progress:5432/progress_service_db
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-default_jwt_secret_for_development_only}
    depends_on:
      - postgres-progress
      - redis
    volumes:
      - ./services/progress-service:/app
      - /app/node_modules
    networks:
      - sharklearning-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    networks:
      - sharklearning-network

volumes:
  postgres_user_data:
  postgres_content_data:
  postgres_progress_data:

networks:
  sharklearning-network:
    driver: bridge 