global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'content-service'
    static_configs:
      - targets: ['content-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'progress-service'
    static_configs:
      - targets: ['progress-service:3021']
    metrics_path: '/metrics'
    scrape_interval: 30s

rule_files:
  # - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093 